site_name: Python for Data Analysis Data Wrangling with pandas, NumPy & Jupyter
theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highligtht
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    scheme: 'slate'
    primary: 'black'
    accent: 'light blue'
  font:
    text: 'Segoe UI'
    code: 'Consolas'

nav:
  - Home: index.md
  # - Lectures:
  #     - Lecture 1: lecture1.md
  #     - Lecture 2: lecture2.md
  # - page2: page2.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search

extra_css:
  - 'stylesheets/extra.css'
