site_name: Python for Data Analysis Data Wrangling with pandas, NumPy & Jupyter
repo_url: https://github.com/on3moy/Python-For-Data-Analysis-Lecture-Notes
repo_name: 'GitHub'

theme:
  logo: img/Brackets.ico
  name: 'material'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highligtht
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    scheme: 'slate'
    primary: 'black'
    accent: 'light blue'
  font:
    text: 'calibri'
    code: 'Consolas'

nav:
  - Home: index.md
  - Lectures:
      - Chatper 1 Preliminaries: book/CH1/Preliminaries.md
      - Chapter 1 NB: book/Notebooks/Ch1.ipynb
  - Python Crash Course: book/Notebooks/Python Crash Course.ipynb

  #     - Lecture 2: lecture2.md
  # - page2: page2.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html

plugins:
  - search
  - mknotebooks

extra_css:
  - 'stylesheets/extra.css'

copyright: Copyright &copy; 2024 Moy Patel